/**
 * @vitest-environment happy-dom
 */

import { describe, expect, it } from 'vitest'
import { render, screen } from '@testing-library/react'
import { PublicCaseStudy } from '@/features/projects/components/public/PublicCaseStudy'
import type { PublicCaseStudy as PublicCaseStudyData } from '@/features/projects/lib/public-types'

function makeData(overrides: Partial<PublicCaseStudyData> = {}): PublicCaseStudyData {
  return {
    username: 'nelson', slug: 'atlas', name: 'Atlas', tagline: 'A platform',
    pitch: 'The pitch.', type: 'production_saas', shape: 'multi_repo',
    status: 'active', roleExhibited: 'sole_builder',
    startedAt: null, endedAt: null, lastActivityAt: null, updatedAt: new Date().toISOString(),
    components: [], repositories: [],
    decisions: [], highlights: [], challenges: [], stack: [],
    depthMarkers: null, architecture: null, resumeBullets: [], tags: [],
    ...overrides,
  }
}

describe('PublicCaseStudy', () => {
  it('renders the name, tagline, and pitch', () => {
    render(<PublicCaseStudy data={makeData()} />)
    expect(screen.getByRole('heading', { level: 1, name: 'Atlas' })).toBeTruthy()
    expect(screen.getByText('A platform')).toBeTruthy()
    expect(screen.getByText('The pitch.')).toBeTruthy()
  })

  it('renders the evidence footer badge', () => {
    render(<PublicCaseStudy data={makeData()} />)
    expect(screen.getByText(/generated by tucaken from real github evidence/i)).toBeTruthy()
  })

  it('renders stack chips grouped under category headings', () => {
    render(<PublicCaseStudy data={makeData({
      stack: [
        { category: 'language',  name: 'TypeScript', justification: null, order_index: 0 },
        { category: 'framework', name: 'React',      justification: null, order_index: 1 },
      ],
    })} />)
    expect(screen.getByText('Languages')).toBeTruthy()
    expect(screen.getByText('TypeScript')).toBeTruthy()
    expect(screen.getByText('Frameworks')).toBeTruthy()
    expect(screen.getByText('React')).toBeTruthy()
  })

  it('omits sections that have no data', () => {
    render(<PublicCaseStudy data={makeData({ pitch: null })} />)
    expect(screen.queryByText('Highlights')).toBeNull()
    expect(screen.queryByText('Challenges')).toBeNull()
    expect(screen.queryByText('Key decisions')).toBeNull()
  })
})
