import { useState } from 'react'
import { Loader2, Sparkles, Copy, Check } from 'lucide-react'
import { Button } from '@/components/ui/Button'

type GenerateStatus = 'idle' | 'generating' | 'done'

const PLACEHOLDER_JD = `Paste the job description here…

Example:
We're looking for a senior backend engineer to join our platform team.
You'll work on distributed systems, own critical infrastructure, and mentor junior engineers.
Required: 5+ years Go or TypeScript, strong systems design, Kubernetes experience.`

const MOCK_RESUME = `# Nelson Lamounier — Senior Platform Engineer

## Summary
Platform engineer with 6+ years building distributed systems on AWS. Led migration of legacy monolith to EKS microservices at Example Corp, cutting p99 latency by 40%. Deep Kubernetes and Go experience.

## Experience

**Senior Software Engineer · Example Corp** (Mar 2021 – Present)
- Architected migration from monolith to 12 microservices on AWS EKS, reducing deploy time from 45 min to 8 min
- Built internal CLI tooling in Go used by 20 engineers daily
- Mentored 3 junior engineers; conducted weekly architecture reviews

## Education
BSc Computer Science · University of Example · 2018

---
*Generated by Tucaken — grounded in your GitHub commit history and career data*`

interface GenerateResumeStepProps {
  readonly onDone?: () => void
}

export function GenerateResumeStep({ onDone }: GenerateResumeStepProps) {
  const [jd, setJd] = useState('')
  const [status, setStatus] = useState<GenerateStatus>('idle')
  const [resume, setResume] = useState<string | null>(null)
  const [copied, setCopied] = useState(false)

  function handleGenerate() {
    if (!jd.trim()) return
    setStatus('generating')
    // Replace with real server fn call
    setTimeout(() => {
      setResume(MOCK_RESUME)
      setStatus('done')
      onDone?.()
    }, 2200)
  }

  async function handleCopy() {
    if (!resume) return
    await navigator.clipboard.writeText(resume)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div className="space-y-6">
      <div>
        <h3 className="text-base font-semibold text-zinc-100">Generate your first resume</h3>
        <p className="mt-1 text-sm text-zinc-500">
          Paste a job description and Tucaken tailors a resume with claims grounded in both your
          code and your enriched career history.
        </p>
      </div>

      <div className="space-y-3">
        <label className="block text-xs font-medium text-zinc-400">Job Description</label>
        <textarea
          value={jd}
          onChange={(e) => setJd(e.target.value)}
          placeholder={PLACEHOLDER_JD}
          rows={8}
          disabled={status === 'generating'}
          className="w-full resize-none rounded-lg border border-white/10 bg-white/[0.04] px-3.5 py-3 text-sm text-zinc-300 placeholder:text-zinc-600 focus:outline-none focus:border-indigo-500/50 disabled:opacity-50 transition-colors"
        />
        <Button
          variant="primary"
          onClick={handleGenerate}
          disabled={!jd.trim() || status === 'generating'}
          className="flex items-center gap-2"
        >
          {status === 'generating' ? (
            <>
              <Loader2 className="h-4 w-4 animate-spin" />
              Generating…
            </>
          ) : (
            <>
              <Sparkles className="h-4 w-4" />
              Generate Resume
            </>
          )}
        </Button>
      </div>

      {resume && (
        <div className="space-y-3">
          <div className="flex items-center justify-between">
            <h4 className="text-xs font-semibold uppercase tracking-wider text-zinc-500">
              Tailored Resume
            </h4>
            <Button
              variant="ghost"
              onClick={() => void handleCopy()}
              className="flex items-center gap-1.5 text-xs"
            >
              {copied ? (
                <>
                  <Check className="h-3.5 w-3.5 text-emerald-400" />
                  <span className="text-emerald-400">Copied</span>
                </>
              ) : (
                <>
                  <Copy className="h-3.5 w-3.5" />
                  Copy
                </>
              )}
            </Button>
          </div>
          <pre className="rounded-lg border border-white/10 bg-white/[0.03] p-4 text-xs leading-relaxed text-zinc-300 whitespace-pre-wrap overflow-auto max-h-96">
            {resume}
          </pre>
        </div>
      )}
    </div>
  )
}
