/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as LoginRouteImport } from './app/login'
import { Route as DashboardRouteImport } from './app/_dashboard'
import { Route as DashboardIndexRouteImport } from './app/_dashboard.index'
import { Route as AuthCallbackRouteImport } from './app/auth.callback'
import { Route as DashboardResumesRouteImport } from './app/_dashboard.resumes'
import { Route as DashboardReportsRouteImport } from './app/_dashboard.reports'
import { Route as DashboardCommentsRouteImport } from './app/_dashboard.comments'
import { Route as DashboardArticlesRouteImport } from './app/_dashboard.articles'
import { Route as DashboardAiAgentRouteImport } from './app/_dashboard.ai-agent'
import { Route as DashboardApplicationsIndexRouteImport } from './app/_dashboard.applications.index'
import { Route as DashboardResumesNewRouteImport } from './app/_dashboard.resumes.new'
import { Route as DashboardEditorSlugRouteImport } from './app/_dashboard.editor.$slug'
import { Route as DashboardApplicationsNewRouteImport } from './app/_dashboard.applications.new'
import { Route as DashboardApplicationsListRouteImport } from './app/_dashboard.applications.list'
import { Route as DashboardApplicationsInterviewPrepRouteImport } from './app/_dashboard.applications.interview-prep'
import { Route as DashboardApplicationsSlugRouteImport } from './app/_dashboard.applications.$slug'
import { Route as DashboardResumesEditIdRouteImport } from './app/_dashboard.resumes.edit.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardResumesRoute = DashboardResumesRouteImport.update({
  id: '/resumes',
  path: '/resumes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCommentsRoute = DashboardCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardArticlesRoute = DashboardArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiAgentRoute = DashboardAiAgentRouteImport.update({
  id: '/ai-agent',
  path: '/ai-agent',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApplicationsIndexRoute =
  DashboardApplicationsIndexRouteImport.update({
    id: '/applications/',
    path: '/applications/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardResumesNewRoute = DashboardResumesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardResumesRoute,
} as any)
const DashboardEditorSlugRoute = DashboardEditorSlugRouteImport.update({
  id: '/editor/$slug',
  path: '/editor/$slug',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApplicationsNewRoute =
  DashboardApplicationsNewRouteImport.update({
    id: '/applications/new',
    path: '/applications/new',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardApplicationsListRoute =
  DashboardApplicationsListRouteImport.update({
    id: '/applications/list',
    path: '/applications/list',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardApplicationsInterviewPrepRoute =
  DashboardApplicationsInterviewPrepRouteImport.update({
    id: '/applications/interview-prep',
    path: '/applications/interview-prep',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardApplicationsSlugRoute =
  DashboardApplicationsSlugRouteImport.update({
    id: '/applications/$slug',
    path: '/applications/$slug',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardResumesEditIdRoute = DashboardResumesEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => DashboardResumesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/login': typeof LoginRoute
  '/ai-agent': typeof DashboardAiAgentRoute
  '/articles': typeof DashboardArticlesRoute
  '/comments': typeof DashboardCommentsRoute
  '/reports': typeof DashboardReportsRoute
  '/resumes': typeof DashboardResumesRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/applications/$slug': typeof DashboardApplicationsSlugRoute
  '/applications/interview-prep': typeof DashboardApplicationsInterviewPrepRoute
  '/applications/list': typeof DashboardApplicationsListRoute
  '/applications/new': typeof DashboardApplicationsNewRoute
  '/editor/$slug': typeof DashboardEditorSlugRoute
  '/resumes/new': typeof DashboardResumesNewRoute
  '/applications/': typeof DashboardApplicationsIndexRoute
  '/resumes/edit/$id': typeof DashboardResumesEditIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/ai-agent': typeof DashboardAiAgentRoute
  '/articles': typeof DashboardArticlesRoute
  '/comments': typeof DashboardCommentsRoute
  '/reports': typeof DashboardReportsRoute
  '/resumes': typeof DashboardResumesRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof DashboardIndexRoute
  '/applications/$slug': typeof DashboardApplicationsSlugRoute
  '/applications/interview-prep': typeof DashboardApplicationsInterviewPrepRoute
  '/applications/list': typeof DashboardApplicationsListRoute
  '/applications/new': typeof DashboardApplicationsNewRoute
  '/editor/$slug': typeof DashboardEditorSlugRoute
  '/resumes/new': typeof DashboardResumesNewRoute
  '/applications': typeof DashboardApplicationsIndexRoute
  '/resumes/edit/$id': typeof DashboardResumesEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/_dashboard/ai-agent': typeof DashboardAiAgentRoute
  '/_dashboard/articles': typeof DashboardArticlesRoute
  '/_dashboard/comments': typeof DashboardCommentsRoute
  '/_dashboard/reports': typeof DashboardReportsRoute
  '/_dashboard/resumes': typeof DashboardResumesRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/applications/$slug': typeof DashboardApplicationsSlugRoute
  '/_dashboard/applications/interview-prep': typeof DashboardApplicationsInterviewPrepRoute
  '/_dashboard/applications/list': typeof DashboardApplicationsListRoute
  '/_dashboard/applications/new': typeof DashboardApplicationsNewRoute
  '/_dashboard/editor/$slug': typeof DashboardEditorSlugRoute
  '/_dashboard/resumes/new': typeof DashboardResumesNewRoute
  '/_dashboard/applications/': typeof DashboardApplicationsIndexRoute
  '/_dashboard/resumes/edit/$id': typeof DashboardResumesEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ai-agent'
    | '/articles'
    | '/comments'
    | '/reports'
    | '/resumes'
    | '/auth/callback'
    | '/applications/$slug'
    | '/applications/interview-prep'
    | '/applications/list'
    | '/applications/new'
    | '/editor/$slug'
    | '/resumes/new'
    | '/applications/'
    | '/resumes/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/ai-agent'
    | '/articles'
    | '/comments'
    | '/reports'
    | '/resumes'
    | '/auth/callback'
    | '/'
    | '/applications/$slug'
    | '/applications/interview-prep'
    | '/applications/list'
    | '/applications/new'
    | '/editor/$slug'
    | '/resumes/new'
    | '/applications'
    | '/resumes/edit/$id'
  id:
    | '__root__'
    | '/_dashboard'
    | '/login'
    | '/_dashboard/ai-agent'
    | '/_dashboard/articles'
    | '/_dashboard/comments'
    | '/_dashboard/reports'
    | '/_dashboard/resumes'
    | '/auth/callback'
    | '/_dashboard/'
    | '/_dashboard/applications/$slug'
    | '/_dashboard/applications/interview-prep'
    | '/_dashboard/applications/list'
    | '/_dashboard/applications/new'
    | '/_dashboard/editor/$slug'
    | '/_dashboard/resumes/new'
    | '/_dashboard/applications/'
    | '/_dashboard/resumes/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/resumes': {
      id: '/_dashboard/resumes'
      path: '/resumes'
      fullPath: '/resumes'
      preLoaderRoute: typeof DashboardResumesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/reports': {
      id: '/_dashboard/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/comments': {
      id: '/_dashboard/comments'
      path: '/comments'
      fullPath: '/comments'
      preLoaderRoute: typeof DashboardCommentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/articles': {
      id: '/_dashboard/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof DashboardArticlesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/ai-agent': {
      id: '/_dashboard/ai-agent'
      path: '/ai-agent'
      fullPath: '/ai-agent'
      preLoaderRoute: typeof DashboardAiAgentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/applications/': {
      id: '/_dashboard/applications/'
      path: '/applications'
      fullPath: '/applications/'
      preLoaderRoute: typeof DashboardApplicationsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/resumes/new': {
      id: '/_dashboard/resumes/new'
      path: '/new'
      fullPath: '/resumes/new'
      preLoaderRoute: typeof DashboardResumesNewRouteImport
      parentRoute: typeof DashboardResumesRoute
    }
    '/_dashboard/editor/$slug': {
      id: '/_dashboard/editor/$slug'
      path: '/editor/$slug'
      fullPath: '/editor/$slug'
      preLoaderRoute: typeof DashboardEditorSlugRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/applications/new': {
      id: '/_dashboard/applications/new'
      path: '/applications/new'
      fullPath: '/applications/new'
      preLoaderRoute: typeof DashboardApplicationsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/applications/list': {
      id: '/_dashboard/applications/list'
      path: '/applications/list'
      fullPath: '/applications/list'
      preLoaderRoute: typeof DashboardApplicationsListRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/applications/interview-prep': {
      id: '/_dashboard/applications/interview-prep'
      path: '/applications/interview-prep'
      fullPath: '/applications/interview-prep'
      preLoaderRoute: typeof DashboardApplicationsInterviewPrepRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/applications/$slug': {
      id: '/_dashboard/applications/$slug'
      path: '/applications/$slug'
      fullPath: '/applications/$slug'
      preLoaderRoute: typeof DashboardApplicationsSlugRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/resumes/edit/$id': {
      id: '/_dashboard/resumes/edit/$id'
      path: '/edit/$id'
      fullPath: '/resumes/edit/$id'
      preLoaderRoute: typeof DashboardResumesEditIdRouteImport
      parentRoute: typeof DashboardResumesRoute
    }
  }
}

interface DashboardResumesRouteChildren {
  DashboardResumesNewRoute: typeof DashboardResumesNewRoute
  DashboardResumesEditIdRoute: typeof DashboardResumesEditIdRoute
}

const DashboardResumesRouteChildren: DashboardResumesRouteChildren = {
  DashboardResumesNewRoute: DashboardResumesNewRoute,
  DashboardResumesEditIdRoute: DashboardResumesEditIdRoute,
}

const DashboardResumesRouteWithChildren =
  DashboardResumesRoute._addFileChildren(DashboardResumesRouteChildren)

interface DashboardRouteChildren {
  DashboardAiAgentRoute: typeof DashboardAiAgentRoute
  DashboardArticlesRoute: typeof DashboardArticlesRoute
  DashboardCommentsRoute: typeof DashboardCommentsRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardResumesRoute: typeof DashboardResumesRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardApplicationsSlugRoute: typeof DashboardApplicationsSlugRoute
  DashboardApplicationsInterviewPrepRoute: typeof DashboardApplicationsInterviewPrepRoute
  DashboardApplicationsListRoute: typeof DashboardApplicationsListRoute
  DashboardApplicationsNewRoute: typeof DashboardApplicationsNewRoute
  DashboardEditorSlugRoute: typeof DashboardEditorSlugRoute
  DashboardApplicationsIndexRoute: typeof DashboardApplicationsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAiAgentRoute: DashboardAiAgentRoute,
  DashboardArticlesRoute: DashboardArticlesRoute,
  DashboardCommentsRoute: DashboardCommentsRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardResumesRoute: DashboardResumesRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardApplicationsSlugRoute: DashboardApplicationsSlugRoute,
  DashboardApplicationsInterviewPrepRoute:
    DashboardApplicationsInterviewPrepRoute,
  DashboardApplicationsListRoute: DashboardApplicationsListRoute,
  DashboardApplicationsNewRoute: DashboardApplicationsNewRoute,
  DashboardEditorSlugRoute: DashboardEditorSlugRoute,
  DashboardApplicationsIndexRoute: DashboardApplicationsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
