/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as SignInRouteImport } from './app/sign-in'
import { Route as PricingRouteImport } from './app/pricing'
import { Route as OnboardingRouteImport } from './app/onboarding'
import { Route as LoginRouteImport } from './app/login'
import { Route as DashboardRouteImport } from './app/_dashboard'
import { Route as IndexRouteImport } from './app/index'
import { Route as SignInCallbackRouteImport } from './app/sign-in.callback'
import { Route as GithubCallbackRouteImport } from './app/github.callback'
import { Route as CheckoutReturnRouteImport } from './app/checkout.return'
import { Route as CheckoutTierRouteImport } from './app/checkout.$tier'
import { Route as DashboardTestRouteImport } from './app/_dashboard.test'
import { Route as DashboardSearchAnalyticsRouteImport } from './app/_dashboard.search-analytics'
import { Route as DashboardResumeThemeRouteImport } from './app/_dashboard.resume-theme'
import { Route as DashboardReportsRouteImport } from './app/_dashboard.reports'
import { Route as DashboardOverviewRouteImport } from './app/_dashboard.overview'
import { Route as DashboardCommentsRouteImport } from './app/_dashboard.comments'
import { Route as DashboardCalendarRouteImport } from './app/_dashboard.calendar'
import { Route as DashboardBillingRouteImport } from './app/_dashboard.billing'
import { Route as DashboardArticlesRouteImport } from './app/_dashboard.articles'
import { Route as DashboardAiAgentRouteImport } from './app/_dashboard.ai-agent'
import { Route as DashboardSplatRouteImport } from './app/_dashboard.$'
import { Route as DashboardResumesRouteRouteImport } from './app/_dashboard/resumes/route'
import { Route as DashboardSettingsIndexRouteImport } from './app/_dashboard.settings.index'
import { Route as DashboardProjectsIndexRouteImport } from './app/_dashboard/projects/index'
import { Route as DashboardApplicationsIndexRouteImport } from './app/_dashboard/applications/index'
import { Route as ArticlesPreviewSlugRouteImport } from './app/articles.preview.$slug'
import { Route as DashboardSettingsGithubRouteImport } from './app/_dashboard.settings.github'
import { Route as DashboardProjectsReviewRouteImport } from './app/_dashboard/projects/review'
import { Route as DashboardProjectsIdRouteImport } from './app/_dashboard/projects/$id'
import { Route as DashboardApplicationsNewRouteImport } from './app/_dashboard/applications/new'
import { Route as DashboardApplicationsListRouteImport } from './app/_dashboard/applications/list'
import { Route as DashboardApplicationsInterviewPrepRouteImport } from './app/_dashboard/applications/interview-prep'
import { Route as DashboardApplicationsSlugRouteImport } from './app/_dashboard/applications/$slug'
import { Route as DashboardResumesNewRouteRouteImport } from './app/_dashboard/resumes/new/route'
import { Route as DashboardAdminUsersRouteRouteImport } from './app/_dashboard/admin/users/route'
import { Route as UUsernamePSlugRouteImport } from './app/u/$username/p/$slug'
import { Route as DashboardProjectsIdEditRouteImport } from './app/_dashboard/projects/$id.edit'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInCallbackRoute = SignInCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => SignInRoute,
} as any)
const GithubCallbackRoute = GithubCallbackRouteImport.update({
  id: '/github/callback',
  path: '/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutTierRoute = CheckoutTierRouteImport.update({
  id: '/checkout/$tier',
  path: '/checkout/$tier',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTestRoute = DashboardTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSearchAnalyticsRoute =
  DashboardSearchAnalyticsRouteImport.update({
    id: '/search-analytics',
    path: '/search-analytics',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardResumeThemeRoute = DashboardResumeThemeRouteImport.update({
  id: '/resume-theme',
  path: '/resume-theme',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOverviewRoute = DashboardOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCommentsRoute = DashboardCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardArticlesRoute = DashboardArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiAgentRoute = DashboardAiAgentRouteImport.update({
  id: '/ai-agent',
  path: '/ai-agent',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSplatRoute = DashboardSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResumesRouteRoute = DashboardResumesRouteRouteImport.update({
  id: '/resumes',
  path: '/resumes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsIndexRoute = DashboardProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApplicationsIndexRoute =
  DashboardApplicationsIndexRouteImport.update({
    id: '/applications/',
    path: '/applications/',
    getParentRoute: () => DashboardRoute,
  } as any)
const ArticlesPreviewSlugRoute = ArticlesPreviewSlugRouteImport.update({
  id: '/articles/preview/$slug',
  path: '/articles/preview/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsGithubRoute = DashboardSettingsGithubRouteImport.update({
  id: '/settings/github',
  path: '/settings/github',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsReviewRoute = DashboardProjectsReviewRouteImport.update({
  id: '/projects/review',
  path: '/projects/review',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsIdRoute = DashboardProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApplicationsNewRoute =
  DashboardApplicationsNewRouteImport.update({
    id: '/applications/new',
    path: '/applications/new',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardApplicationsListRoute =
  DashboardApplicationsListRouteImport.update({
    id: '/applications/list',
    path: '/applications/list',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardApplicationsInterviewPrepRoute =
  DashboardApplicationsInterviewPrepRouteImport.update({
    id: '/applications/interview-prep',
    path: '/applications/interview-prep',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardApplicationsSlugRoute =
  DashboardApplicationsSlugRouteImport.update({
    id: '/applications/$slug',
    path: '/applications/$slug',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardResumesNewRouteRoute =
  DashboardResumesNewRouteRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => DashboardResumesRouteRoute,
  } as any)
const DashboardAdminUsersRouteRoute =
  DashboardAdminUsersRouteRouteImport.update({
    id: '/admin/users',
    path: '/admin/users',
    getParentRoute: () => DashboardRoute,
  } as any)
const UUsernamePSlugRoute = UUsernamePSlugRouteImport.update({
  id: '/u/$username/p/$slug',
  path: '/u/$username/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProjectsIdEditRoute = DashboardProjectsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => DashboardProjectsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/resumes': typeof DashboardResumesRouteRouteWithChildren
  '/$': typeof DashboardSplatRoute
  '/ai-agent': typeof DashboardAiAgentRoute
  '/articles': typeof DashboardArticlesRoute
  '/billing': typeof DashboardBillingRoute
  '/calendar': typeof DashboardCalendarRoute
  '/comments': typeof DashboardCommentsRoute
  '/overview': typeof DashboardOverviewRoute
  '/reports': typeof DashboardReportsRoute
  '/resume-theme': typeof DashboardResumeThemeRoute
  '/search-analytics': typeof DashboardSearchAnalyticsRoute
  '/test': typeof DashboardTestRoute
  '/checkout/$tier': typeof CheckoutTierRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/github/callback': typeof GithubCallbackRoute
  '/sign-in/callback': typeof SignInCallbackRoute
  '/admin/users': typeof DashboardAdminUsersRouteRoute
  '/resumes/new': typeof DashboardResumesNewRouteRoute
  '/applications/$slug': typeof DashboardApplicationsSlugRoute
  '/applications/interview-prep': typeof DashboardApplicationsInterviewPrepRoute
  '/applications/list': typeof DashboardApplicationsListRoute
  '/applications/new': typeof DashboardApplicationsNewRoute
  '/projects/$id': typeof DashboardProjectsIdRouteWithChildren
  '/projects/review': typeof DashboardProjectsReviewRoute
  '/settings/github': typeof DashboardSettingsGithubRoute
  '/articles/preview/$slug': typeof ArticlesPreviewSlugRoute
  '/applications/': typeof DashboardApplicationsIndexRoute
  '/projects/': typeof DashboardProjectsIndexRoute
  '/settings/': typeof DashboardSettingsIndexRoute
  '/projects/$id/edit': typeof DashboardProjectsIdEditRoute
  '/u/$username/p/$slug': typeof UUsernamePSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/resumes': typeof DashboardResumesRouteRouteWithChildren
  '/$': typeof DashboardSplatRoute
  '/ai-agent': typeof DashboardAiAgentRoute
  '/articles': typeof DashboardArticlesRoute
  '/billing': typeof DashboardBillingRoute
  '/calendar': typeof DashboardCalendarRoute
  '/comments': typeof DashboardCommentsRoute
  '/overview': typeof DashboardOverviewRoute
  '/reports': typeof DashboardReportsRoute
  '/resume-theme': typeof DashboardResumeThemeRoute
  '/search-analytics': typeof DashboardSearchAnalyticsRoute
  '/test': typeof DashboardTestRoute
  '/checkout/$tier': typeof CheckoutTierRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/github/callback': typeof GithubCallbackRoute
  '/sign-in/callback': typeof SignInCallbackRoute
  '/admin/users': typeof DashboardAdminUsersRouteRoute
  '/resumes/new': typeof DashboardResumesNewRouteRoute
  '/applications/$slug': typeof DashboardApplicationsSlugRoute
  '/applications/interview-prep': typeof DashboardApplicationsInterviewPrepRoute
  '/applications/list': typeof DashboardApplicationsListRoute
  '/applications/new': typeof DashboardApplicationsNewRoute
  '/projects/$id': typeof DashboardProjectsIdRouteWithChildren
  '/projects/review': typeof DashboardProjectsReviewRoute
  '/settings/github': typeof DashboardSettingsGithubRoute
  '/articles/preview/$slug': typeof ArticlesPreviewSlugRoute
  '/applications': typeof DashboardApplicationsIndexRoute
  '/projects': typeof DashboardProjectsIndexRoute
  '/settings': typeof DashboardSettingsIndexRoute
  '/projects/$id/edit': typeof DashboardProjectsIdEditRoute
  '/u/$username/p/$slug': typeof UUsernamePSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/_dashboard/resumes': typeof DashboardResumesRouteRouteWithChildren
  '/_dashboard/$': typeof DashboardSplatRoute
  '/_dashboard/ai-agent': typeof DashboardAiAgentRoute
  '/_dashboard/articles': typeof DashboardArticlesRoute
  '/_dashboard/billing': typeof DashboardBillingRoute
  '/_dashboard/calendar': typeof DashboardCalendarRoute
  '/_dashboard/comments': typeof DashboardCommentsRoute
  '/_dashboard/overview': typeof DashboardOverviewRoute
  '/_dashboard/reports': typeof DashboardReportsRoute
  '/_dashboard/resume-theme': typeof DashboardResumeThemeRoute
  '/_dashboard/search-analytics': typeof DashboardSearchAnalyticsRoute
  '/_dashboard/test': typeof DashboardTestRoute
  '/checkout/$tier': typeof CheckoutTierRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/github/callback': typeof GithubCallbackRoute
  '/sign-in/callback': typeof SignInCallbackRoute
  '/_dashboard/admin/users': typeof DashboardAdminUsersRouteRoute
  '/_dashboard/resumes/new': typeof DashboardResumesNewRouteRoute
  '/_dashboard/applications/$slug': typeof DashboardApplicationsSlugRoute
  '/_dashboard/applications/interview-prep': typeof DashboardApplicationsInterviewPrepRoute
  '/_dashboard/applications/list': typeof DashboardApplicationsListRoute
  '/_dashboard/applications/new': typeof DashboardApplicationsNewRoute
  '/_dashboard/projects/$id': typeof DashboardProjectsIdRouteWithChildren
  '/_dashboard/projects/review': typeof DashboardProjectsReviewRoute
  '/_dashboard/settings/github': typeof DashboardSettingsGithubRoute
  '/articles/preview/$slug': typeof ArticlesPreviewSlugRoute
  '/_dashboard/applications/': typeof DashboardApplicationsIndexRoute
  '/_dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/_dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/_dashboard/projects/$id/edit': typeof DashboardProjectsIdEditRoute
  '/u/$username/p/$slug': typeof UUsernamePSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/sign-in'
    | '/resumes'
    | '/$'
    | '/ai-agent'
    | '/articles'
    | '/billing'
    | '/calendar'
    | '/comments'
    | '/overview'
    | '/reports'
    | '/resume-theme'
    | '/search-analytics'
    | '/test'
    | '/checkout/$tier'
    | '/checkout/return'
    | '/github/callback'
    | '/sign-in/callback'
    | '/admin/users'
    | '/resumes/new'
    | '/applications/$slug'
    | '/applications/interview-prep'
    | '/applications/list'
    | '/applications/new'
    | '/projects/$id'
    | '/projects/review'
    | '/settings/github'
    | '/articles/preview/$slug'
    | '/applications/'
    | '/projects/'
    | '/settings/'
    | '/projects/$id/edit'
    | '/u/$username/p/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/sign-in'
    | '/resumes'
    | '/$'
    | '/ai-agent'
    | '/articles'
    | '/billing'
    | '/calendar'
    | '/comments'
    | '/overview'
    | '/reports'
    | '/resume-theme'
    | '/search-analytics'
    | '/test'
    | '/checkout/$tier'
    | '/checkout/return'
    | '/github/callback'
    | '/sign-in/callback'
    | '/admin/users'
    | '/resumes/new'
    | '/applications/$slug'
    | '/applications/interview-prep'
    | '/applications/list'
    | '/applications/new'
    | '/projects/$id'
    | '/projects/review'
    | '/settings/github'
    | '/articles/preview/$slug'
    | '/applications'
    | '/projects'
    | '/settings'
    | '/projects/$id/edit'
    | '/u/$username/p/$slug'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/sign-in'
    | '/_dashboard/resumes'
    | '/_dashboard/$'
    | '/_dashboard/ai-agent'
    | '/_dashboard/articles'
    | '/_dashboard/billing'
    | '/_dashboard/calendar'
    | '/_dashboard/comments'
    | '/_dashboard/overview'
    | '/_dashboard/reports'
    | '/_dashboard/resume-theme'
    | '/_dashboard/search-analytics'
    | '/_dashboard/test'
    | '/checkout/$tier'
    | '/checkout/return'
    | '/github/callback'
    | '/sign-in/callback'
    | '/_dashboard/admin/users'
    | '/_dashboard/resumes/new'
    | '/_dashboard/applications/$slug'
    | '/_dashboard/applications/interview-prep'
    | '/_dashboard/applications/list'
    | '/_dashboard/applications/new'
    | '/_dashboard/projects/$id'
    | '/_dashboard/projects/review'
    | '/_dashboard/settings/github'
    | '/articles/preview/$slug'
    | '/_dashboard/applications/'
    | '/_dashboard/projects/'
    | '/_dashboard/settings/'
    | '/_dashboard/projects/$id/edit'
    | '/u/$username/p/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  SignInRoute: typeof SignInRouteWithChildren
  CheckoutTierRoute: typeof CheckoutTierRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  GithubCallbackRoute: typeof GithubCallbackRoute
  ArticlesPreviewSlugRoute: typeof ArticlesPreviewSlugRoute
  UUsernamePSlugRoute: typeof UUsernamePSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/callback': {
      id: '/sign-in/callback'
      path: '/callback'
      fullPath: '/sign-in/callback'
      preLoaderRoute: typeof SignInCallbackRouteImport
      parentRoute: typeof SignInRoute
    }
    '/github/callback': {
      id: '/github/callback'
      path: '/github/callback'
      fullPath: '/github/callback'
      preLoaderRoute: typeof GithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$tier': {
      id: '/checkout/$tier'
      path: '/checkout/$tier'
      fullPath: '/checkout/$tier'
      preLoaderRoute: typeof CheckoutTierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/test': {
      id: '/_dashboard/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof DashboardTestRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/search-analytics': {
      id: '/_dashboard/search-analytics'
      path: '/search-analytics'
      fullPath: '/search-analytics'
      preLoaderRoute: typeof DashboardSearchAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/resume-theme': {
      id: '/_dashboard/resume-theme'
      path: '/resume-theme'
      fullPath: '/resume-theme'
      preLoaderRoute: typeof DashboardResumeThemeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/reports': {
      id: '/_dashboard/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/overview': {
      id: '/_dashboard/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof DashboardOverviewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/comments': {
      id: '/_dashboard/comments'
      path: '/comments'
      fullPath: '/comments'
      preLoaderRoute: typeof DashboardCommentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/calendar': {
      id: '/_dashboard/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/billing': {
      id: '/_dashboard/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/articles': {
      id: '/_dashboard/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof DashboardArticlesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/ai-agent': {
      id: '/_dashboard/ai-agent'
      path: '/ai-agent'
      fullPath: '/ai-agent'
      preLoaderRoute: typeof DashboardAiAgentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/$': {
      id: '/_dashboard/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof DashboardSplatRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/resumes': {
      id: '/_dashboard/resumes'
      path: '/resumes'
      fullPath: '/resumes'
      preLoaderRoute: typeof DashboardResumesRouteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/': {
      id: '/_dashboard/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/projects/': {
      id: '/_dashboard/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof DashboardProjectsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/applications/': {
      id: '/_dashboard/applications/'
      path: '/applications'
      fullPath: '/applications/'
      preLoaderRoute: typeof DashboardApplicationsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/articles/preview/$slug': {
      id: '/articles/preview/$slug'
      path: '/articles/preview/$slug'
      fullPath: '/articles/preview/$slug'
      preLoaderRoute: typeof ArticlesPreviewSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/settings/github': {
      id: '/_dashboard/settings/github'
      path: '/settings/github'
      fullPath: '/settings/github'
      preLoaderRoute: typeof DashboardSettingsGithubRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/projects/review': {
      id: '/_dashboard/projects/review'
      path: '/projects/review'
      fullPath: '/projects/review'
      preLoaderRoute: typeof DashboardProjectsReviewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/projects/$id': {
      id: '/_dashboard/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof DashboardProjectsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/applications/new': {
      id: '/_dashboard/applications/new'
      path: '/applications/new'
      fullPath: '/applications/new'
      preLoaderRoute: typeof DashboardApplicationsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/applications/list': {
      id: '/_dashboard/applications/list'
      path: '/applications/list'
      fullPath: '/applications/list'
      preLoaderRoute: typeof DashboardApplicationsListRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/applications/interview-prep': {
      id: '/_dashboard/applications/interview-prep'
      path: '/applications/interview-prep'
      fullPath: '/applications/interview-prep'
      preLoaderRoute: typeof DashboardApplicationsInterviewPrepRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/applications/$slug': {
      id: '/_dashboard/applications/$slug'
      path: '/applications/$slug'
      fullPath: '/applications/$slug'
      preLoaderRoute: typeof DashboardApplicationsSlugRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/resumes/new': {
      id: '/_dashboard/resumes/new'
      path: '/new'
      fullPath: '/resumes/new'
      preLoaderRoute: typeof DashboardResumesNewRouteRouteImport
      parentRoute: typeof DashboardResumesRouteRoute
    }
    '/_dashboard/admin/users': {
      id: '/_dashboard/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/u/$username/p/$slug': {
      id: '/u/$username/p/$slug'
      path: '/u/$username/p/$slug'
      fullPath: '/u/$username/p/$slug'
      preLoaderRoute: typeof UUsernamePSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/projects/$id/edit': {
      id: '/_dashboard/projects/$id/edit'
      path: '/edit'
      fullPath: '/projects/$id/edit'
      preLoaderRoute: typeof DashboardProjectsIdEditRouteImport
      parentRoute: typeof DashboardProjectsIdRoute
    }
  }
}

interface DashboardResumesRouteRouteChildren {
  DashboardResumesNewRouteRoute: typeof DashboardResumesNewRouteRoute
}

const DashboardResumesRouteRouteChildren: DashboardResumesRouteRouteChildren = {
  DashboardResumesNewRouteRoute: DashboardResumesNewRouteRoute,
}

const DashboardResumesRouteRouteWithChildren =
  DashboardResumesRouteRoute._addFileChildren(
    DashboardResumesRouteRouteChildren,
  )

interface DashboardProjectsIdRouteChildren {
  DashboardProjectsIdEditRoute: typeof DashboardProjectsIdEditRoute
}

const DashboardProjectsIdRouteChildren: DashboardProjectsIdRouteChildren = {
  DashboardProjectsIdEditRoute: DashboardProjectsIdEditRoute,
}

const DashboardProjectsIdRouteWithChildren =
  DashboardProjectsIdRoute._addFileChildren(DashboardProjectsIdRouteChildren)

interface DashboardRouteChildren {
  DashboardResumesRouteRoute: typeof DashboardResumesRouteRouteWithChildren
  DashboardSplatRoute: typeof DashboardSplatRoute
  DashboardAiAgentRoute: typeof DashboardAiAgentRoute
  DashboardArticlesRoute: typeof DashboardArticlesRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardCommentsRoute: typeof DashboardCommentsRoute
  DashboardOverviewRoute: typeof DashboardOverviewRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardResumeThemeRoute: typeof DashboardResumeThemeRoute
  DashboardSearchAnalyticsRoute: typeof DashboardSearchAnalyticsRoute
  DashboardTestRoute: typeof DashboardTestRoute
  DashboardAdminUsersRouteRoute: typeof DashboardAdminUsersRouteRoute
  DashboardApplicationsSlugRoute: typeof DashboardApplicationsSlugRoute
  DashboardApplicationsInterviewPrepRoute: typeof DashboardApplicationsInterviewPrepRoute
  DashboardApplicationsListRoute: typeof DashboardApplicationsListRoute
  DashboardApplicationsNewRoute: typeof DashboardApplicationsNewRoute
  DashboardProjectsIdRoute: typeof DashboardProjectsIdRouteWithChildren
  DashboardProjectsReviewRoute: typeof DashboardProjectsReviewRoute
  DashboardSettingsGithubRoute: typeof DashboardSettingsGithubRoute
  DashboardApplicationsIndexRoute: typeof DashboardApplicationsIndexRoute
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardResumesRouteRoute: DashboardResumesRouteRouteWithChildren,
  DashboardSplatRoute: DashboardSplatRoute,
  DashboardAiAgentRoute: DashboardAiAgentRoute,
  DashboardArticlesRoute: DashboardArticlesRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardCommentsRoute: DashboardCommentsRoute,
  DashboardOverviewRoute: DashboardOverviewRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardResumeThemeRoute: DashboardResumeThemeRoute,
  DashboardSearchAnalyticsRoute: DashboardSearchAnalyticsRoute,
  DashboardTestRoute: DashboardTestRoute,
  DashboardAdminUsersRouteRoute: DashboardAdminUsersRouteRoute,
  DashboardApplicationsSlugRoute: DashboardApplicationsSlugRoute,
  DashboardApplicationsInterviewPrepRoute:
    DashboardApplicationsInterviewPrepRoute,
  DashboardApplicationsListRoute: DashboardApplicationsListRoute,
  DashboardApplicationsNewRoute: DashboardApplicationsNewRoute,
  DashboardProjectsIdRoute: DashboardProjectsIdRouteWithChildren,
  DashboardProjectsReviewRoute: DashboardProjectsReviewRoute,
  DashboardSettingsGithubRoute: DashboardSettingsGithubRoute,
  DashboardApplicationsIndexRoute: DashboardApplicationsIndexRoute,
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface SignInRouteChildren {
  SignInCallbackRoute: typeof SignInCallbackRoute
}

const SignInRouteChildren: SignInRouteChildren = {
  SignInCallbackRoute: SignInCallbackRoute,
}

const SignInRouteWithChildren =
  SignInRoute._addFileChildren(SignInRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  SignInRoute: SignInRouteWithChildren,
  CheckoutTierRoute: CheckoutTierRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  GithubCallbackRoute: GithubCallbackRoute,
  ArticlesPreviewSlugRoute: ArticlesPreviewSlugRoute,
  UUsernamePSlugRoute: UUsernamePSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
